# Generated by Django 2.2.3 on 2019-07-15 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_density'),
    ]

    operations = [
        migrations.RenameField(
            model_name='density',
            old_name='dm',
            new_name='density',
        ),
    ]
