# Generated by Django 2.2.3 on 2019-07-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20190715_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ground', models.ImageField(upload_to='image')),
            ],
        ),
    ]
